name: dagger
on:
  workflow_dispatch:

jobs:
   build-and-test:
      name: build-and-test
      runs-on: ubicloud-standard-2-ubuntu-2404
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Check docker exist
           run: docker info

         - name: Build and Test Kotlin App
           uses: dagger/dagger-for-github@8.0.0
           with:
              version: "latest"
              module: ./.dagger
              args: build-and-test --source=ktor-sample