name: dagger
on:
  workflow_dispatch:

jobs:
   build-and-test:
      name: build-and-test
      runs-on: ${{ matrix.runs-on }}
      strategy:
        matrix:
          runs-on: [ubicloud-standard-4-ubuntu-2404, ubuntu-latest]
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Configure Docker
           run: |
             # Configure Docker to use Docker Hub directly without mirrors
             sudo mkdir -p /etc/docker
             echo '{
               "registry-mirrors": []
             }' | sudo tee /etc/docker/daemon.json
             sudo systemctl restart docker

         - name: Docker info
           run: docker info

         - name: Build and Test Kotlin App
           uses: dagger/dagger-for-github@8.0.0
           with:
              version: "latest"
              module: ./.dagger
              args: build-and-test --source=ktor-sample