name: dagger
on:
  workflow_dispatch:

jobs:
   build-and-test:
      name: build-and-test
      runs-on: ${{ matrix.runs-on }}
      strategy:
        matrix:
          runs-on: [ubicloud-standard-4-ubuntu-2404, ubuntu-latest]
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Docker info
           run: docker info

         - name: Network Diagnostics
           run: |
             echo "Testing network connectivity..."
             curl -v https://registry-1.docker.io/v2/
             echo "Testing DNS resolution..."
             nslookup registry-1.docker.io
             echo "Checking Docker daemon..."
             docker info
             echo "Testing Docker Hub connectivity..."
             docker pull alpine:3.19
             docker save alpine:3.19 > alpine.tar
             docker load < alpine.tar

         - name: Build and Test Kotlin App
           uses: dagger/dagger-for-github@8.0.0
           with:
              version: "latest"
              module: ./.dagger
              args: build-and-test --source=ktor-sample