name: dagger
on:
  workflow_dispatch:

jobs:
   build-and-test:
      name: build-and-test
      runs-on: ${{ matrix.runs-on }}
      strategy:
        matrix:
          runs-on: [ubicloud-standard-4-ubuntu-2404, ubuntu-latest]
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Docker info
           run: docker info

         - name: Test Docker from Container
           run: |
             echo "=== Before Docker-in-Docker ==="
             docker images | grep alpine || echo "No Alpine image found"
             
             echo "=== Starting Docker-in-Docker ==="
             docker run --rm \
               -v /var/run/docker.sock:/var/run/docker.sock \
               docker:latest \
               sh -c 'echo "Inside container: $(docker images)" && docker pull alpine:3.19 && echo "Pull completed" && docker images | grep alpine'
             
             echo "=== After Docker-in-Docker ==="
             docker images | grep alpine || echo "No Alpine image found"

         - name: Build and Test Kotlin App
           uses: dagger/dagger-for-github@8.0.0
           with:
              version: "latest"
              module: ./.dagger
              args: build-and-test --source=ktor-sample